### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by officalunimoghd** [kawacode/gorequest#3]
When i set a proxy ```bot.HttpRequest.Request.Proxy = "http://127.0.0.1:9090"``` i get the following error: 

Console log: 
```
2022/10/09 10:53:59 Get "https://tls.peet.ws/api/all": proxy: unknown scheme: http
panic: Get "https://tls.peet.ws/api/all": proxy: unknown scheme: http
```

**Comment by kawacode** [comment]
This issue has been fixed at version [v1.0.6](https://github.com/kawacode/gorequest/releases/tag/v1.0.6)
Feel free to reopen the issue, if the issue is still.

**Comment by officalunimoghd** [comment]
I get the same error with  this version v1.0.8

**Comment by kawacode** [comment]
Can you please send me the code, which you used?

**Comment by officalunimoghd** [comment]
This is my test file:

```
package main

import (
	gorequest "github.com/kawacode/gorequest"
	gostruct "github.com/kawacode/gostruct"
	"github.com/kawacode/gotools"
)

func main() {
	var bot gostruct.BotData                                                                                                                                                               // Creating a variable called `bot` and setting it to the type `gostruct.BotData`.
	bot.HttpRequest.Request.URL = "https://tls.peet.ws/api/all"                                                                                                                            // Setting the URL of the request.
	bot.HttpRequest.Request.Method = "GET"                                                                                                                                                 // Used to set the method of the request.
	bot.HttpRequest.Request.Protocol = "2"                                                                                                                                                 // Used to set the protocol version of the request.
	bot.HttpRequest.Request.ReadResponseBody = true                                                                                                                                        // Used to read the body from the server.
	bot.HttpRequest.Request.ReadResponseCookies = true                                                                                                                                     // Used to read the cookies from the server.
	bot.HttpRequest.Request.ReadResponseHeaders = true                                                                                                                                     // Used to read the headers from the server.
	bot.HttpRequest.Request.HelloClient = *gotools.GetHelloClient("HelloCustom")                                                                                                           // Setting the JA3 fingerprint of the request.
	bot.HttpRequest.Request.Ja3 = "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28,29-23-24-25-0-1,0" // Setting the JA3 fingerprint of the request.
	bot.HttpRequest.Request.Proxy = "http://127.0.0.1:9090"
	// Setting the proxy of the request. Supported types: ( "proxyless","http", "https", "socks4", "socks4a", "socks5" ), Without Auth format: type://example.com:port
	gorequest.HttpRequest(&bot)              // A function that is used to send a request to the server.
	println(bot.HttpRequest.Response.Source) // Printing the response from the server.
}
```

This is my go.mod

```
module TestGo

go 1.19

require (
	github.com/andybalholm/brotli v1.0.4 // indirect
	github.com/bogdanfinn/utls v1.1.0 // indirect
	github.com/gofiber/fiber/v2 v2.37.0 // indirect
	github.com/kawacode/fhttp v0.4.5 // indirect
	github.com/kawacode/goproxy v1.0.4 // indirect
	github.com/kawacode/gorequest v1.0.8 // indirect
	github.com/kawacode/gostruct v1.0.3 // indirect
	github.com/kawacode/gotools v1.0.8 // indirect
	github.com/kawacode/utls v1.1.4 // indirect
	github.com/klauspost/compress v1.15.0 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasthttp v1.39.0 // indirect
	github.com/valyala/tcplisten v1.0.0 // indirect
	golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4 // indirect
	golang.org/x/net v0.0.0-20220420153159-1850ba15e1be // indirect
	golang.org/x/sys v0.0.0-20220227234510-4e6760a101f9 // indirect
	golang.org/x/text v0.3.7 // indirect
)
```

**Comment by officalunimoghd** [comment]
Did I add it correctly? When I run it I get an error

My code: 

```
package main

import (
	"github.com/kawacode/goproxy"
	gorequest "github.com/kawacode/gorequest"
	gostruct "github.com/kawacode/gostruct"
	"github.com/kawacode/gotools"
)

func main() {
	goproxy.RegisterProxyDialers()
	var bot gostruct.BotData
	// Creating a variable called `bot` and setting it to the type `gostruct.BotData`.
	bot.HttpRequest.Request.URL = "https://tls.peet.ws/api/all"                                                                                                                            // Setting the URL of the request.
	bot.HttpRequest.Request.Method = "GET"                                                                                                                                                 // Used to set the method of the request.
	bot.HttpRequest.Request.Protocol = "2"                                                                                                                                                 // Used to set the protocol version of the request.
	bot.HttpRequest.Request.ReadResponseBody = true                                                                                                                                        // Used to read the body from the server.
	bot.HttpRequest.Request.ReadResponseCookies = true                                                                                                                                     // Used to read the cookies from the server.
	bot.HttpRequest.Request.ReadResponseHeaders = true                                                                                                                                     // Used to read the headers from the server.
	bot.HttpRequest.Request.HelloClient = *gotools.GetHelloClient("HelloCustom")                                                                                                           // Setting the JA3 fingerprint of the request.
	bot.HttpRequest.Request.Ja3 = "771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-156-157-47-53,0-23-65281-10-11-16-5-34-51-43-13-45-28,29-23-24-25-0-1,0" // Setting the JA3 fingerprint of the request.
	bot.HttpRequest.Request.Proxy = "http://127.0.0.1:9090"
	// Setting the proxy of the request. Supported types: ( "proxyless","http", "https", "socks4", "socks4a", "socks5" ), Without Auth format: type://example.com:port
	gorequest.HttpRequest(&bot)              // A function that is used to send a request to the server.
	println(bot.HttpRequest.Response.Source) // Printing the response from the server.
}
```

Console: 
```
2022/10/17 22:23:22 Get "https://tls.peet.ws/api/all": unexpected EOF
panic: Get "https://tls.peet.ws/api/all": unexpected EOF

goroutine 1 [running]:
log.Panic({0xc00012be20?, 0xc000174000?, 0x13e1355?})
        /usr/local/go/src/log/log.go:388 +0x65
github.com/kawacode/gorequest.HttpRequest(0xc000005400)
...
```

**Comment by kawacode** [comment]
Yes, everything is fine, except your ja3. You will have to wait until next Update. I am adding spoofing by fingerprint byte, which makes spoofing easier.

**Comment by officalunimoghd** [comment]
I have updated my user agent, the same error occurs. If I comment out the proxy it works with the same user agent

**Comment by kawacode** [comment]
It could be a problem of your proxy, try another proxy.

**Comment by officalunimoghd** [comment]
I have tried it with several proxies. The request never arrives at the proxies.

**Comment by kawacode** [comment]
Alright, i will let this issue open for now. I will try to fix it in the next version.

**Comment by kawacode** [comment]
> localhost

Why would try to connect over localhost proxy to a server ?

**Comment by officalunimoghd** [comment]
I wanted to analyze the traffic with Proxyman/Fiddler, so I routed it through a Local Proxy.

**Comment by kawacode** [comment]
To enable debugging mode you need to do 
```go
bot.HttpRequest.Request.InsecureSkipVerify = true // Turn on debugging mode.

```

**Comment by officalunimoghd** [comment]
I tried it. I get this error. I am using the newest version


```
2022/11/16 09:34:29 Get "https://tls.peet.ws/api/all": proxy: unknown scheme: http
panic: Get "https://tls.peet.ws/api/all": proxy: unknown scheme: http

goroutine 1 [running]:
log.Panic({0xc00012be20?, 0xc000174000?, 0x13d74f8?})
        /usr/local/go/src/log/log.go:388 +0x65
github.com/kawacode/gorequest.HttpRequest(0xc000026b40)
```

**Comment by officalunimoghd** [comment]
Yeah this is working
